name: Continous Integration

on: pull_request

jobs:
  conntinous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Using Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install -r requirements.txt 
      - run: pytest .\app\test\test.py
